### ISSUE TITLE
DynamoDb.SQL.InvalidQueryException when table names have '_' underscore characters

### ISSUE THREAD

**Issue by zairnamlas** [fsprojects/DynamoDb.SQL#26]
Hi there,
I'm getting DynamoDb.SQL.InvalidQueryException when table name has underscores in it. It works fine for other tables without such character. I'm not able to find where it is check for underscores in the table names but it is definitly splitting on the bases of it. (Can't understand F# Code).

Can you let me know how to fix this? Is there any other limitation in table names?

**Comment by theburningmonk** [comment]
This was fixed in version 2.1.0, can you get the latest version from Nuget and see if it fixes the problem?

**Comment by theburningmonk** [comment]
the line that fixed this was https://github.com/fsprojects/DynamoDb.SQL/blob/develop/src/DynamoDb.SQL/parser.fs#L70

**Comment by zairnamlas** [comment]
First of all thanks for quick reply.

Is it the case that the passed table name is ignored and the type passed is
used as table name.

I have following not working for table name 'tbl_user' but working for
'User'

// Not Working (not returning any results even though there are
results available)

User user = context.ExecQuery<User>("SELECT * FROM tbl_user WHERE Id =
400000000323680").First();

// Working (returning the results)

User user = context.ExecQuery<User>("SELECT * FROM User WHERE Id =
400000000323680").First();




Regards,
Salman Riaz

**Comment by theburningmonk** [comment]
I just tried this on v2.1.0 and it works if the User type has the `DynamoDBTable` attribute with table name set to `tbl_user`, otherwise the AWSSDK throws an exception:

`Amazon.DynamoDBv2.Model.ResourceNotFoundException: Requested resource not found: Table: User not found ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.`

as it's ignoring the table name I'm passing through in the query, but the query was parsed successfully (not getting the `InvalidQueryException`)

**Comment by theburningmonk** [comment]
@zairnamlas did that answer your question by the way?

**Comment by zairnamlas** [comment]
Yes, That is the solution for this problem. But I'm having issues with it as my POCOs are in a different assembly and I don't want to introduce any DynamoDb related logic on them.

Is there a way to do it without specifying this Attribute or to attach this attribute in a different class?
Another question: When you are planning to update AWSSDK as they have now separated packeges for separate functionalities i.e., AWSSDK - Amazon DynamoDB.

I have tried that new package with the source code of yours and it worked fine.

**Comment by theburningmonk** [comment]
WRT AWSSDK, thanks for checking it out! ;-) I'll move to it soon, just wanted to make sure there's no weird issues when you have both the full blown AWSSDK as well as the new service-specific packages in your app. I imagine lots people (like myself) are going to migrate to the new packages gradually rather than a big bang approach and update all their projects at the same time.
I'll find sometime to test it out properly this weekend.

As for the problem of having to decorate domain entities with DynamoDB attributes, we have similar concerns where we wanted to keep the domain entities clean (and not have them somehow tied to the DB storage system we use, which I assume is your motivation as well).
For that, we experimented with couple of approaches depending on the situation:

1. drop down a level of abstraction and use the DynamoDB client directly and construct the POCO from the response manually; you can still use the DynamoDB.SQL syntax with the DynamoDB client. I find this approach is sufficient in small isolated places but for more complicated domains it's just not worth the hassle;

2. have a separate layer of types for DB storage and put all your DynamoDB attributes there (similar to how you have DTOs and decorate them with serialization attributes), where you can apply the DynamoDB attributes and maybe use something like `ValueInjector` to copy properties across. In cases where you don't need the queriability you can also **cheat** by having a generic wrapper, e.g.
```
[DynamoDBTable("foo")]
public class Wrapper<T>
{
    [DynamoDBHashKey]
    public string Id { get; set; }

    [DynamoDBProperty(typeof(MyAwesomeJSONPropertyFormatter))]
    public T Precious { get; set; }
}
```
Neither approach feel satisfying, and option 2 can add quite a bit of work and duplication as well.

**Comment by zairnamlas** [comment]
You answered it nicely. Both approaches are introducing a lot of work. I'll
think about it what to do with that.

WRT AWSSDK, You don't need both old and new. You just need functionality
specific package and it depends on a new Core project.

**Comment by theburningmonk** [comment]
For this library I won't, but my worry is with the people that use DynamoDB.SQL as they probably still have dependency on the full AWSSDK and I just need to make sure it doesn't cause any conflicts or weird issues for them.

**Comment by zairnamlas** [comment]
Ah, Got it.

**Comment by theburningmonk** [comment]
I've opened a new issue #27 for the move to new AWSSDK, and will close this one now
