### ISSUE TITLE
Long numbers are not working

### ISSUE THREAD

**Issue by zairnamlas** [fsprojects/DynamoDb.SQL#28]
Hi there again,
I have just noticed that the long numbers are not working in sql.
Consider the following two examples

// Not working even the data is present
SELECT * FROM pd_cs_chatroomuser WHERE UserId = 10205471065416056 WITH(Index(UserIdIndex, false), NoConsistentRead)

// Working 
SELECT * FROM pd_cs_chatroomuser WHERE UserId = 10205471065 WITH(Index(UserIdIndex, false), NoConsistentRead)

**Comment by theburningmonk** [comment]
Do you get any exceptions? or just not get any results back when you run
the query?

**Comment by theburningmonk** [comment]
I think what's happening is that, the integer value gets converted to int32
which overflows in this case so by the time it's converted to a request to
DynamoDB it's sending through a negative number instead.

**Comment by zairnamlas** [comment]
Yeah, looks like that is the case. No exception and no results coming back.
Is it a quick fix?

**Comment by theburningmonk** [comment]
Yup, should be straight forward, will fix it tonight

**Comment by zairnamlas** [comment]
Thanks, let me know the changes as I'm using inline project of yours with latest AWS SDK. I can apply those changes in my version of the code.

**Comment by theburningmonk** [comment]
@zairnamlas took a little longer than I had before a bank holiday weekend trip but turns out the parser was fine, it was a problem when the float was translated to a DynamoDB request because the default behaviour of `ToString` is to use scientific notation on large floating point numbers.

In the end it was a very simple fix though, which was to use the `r` formatting string https://msdn.microsoft.com/en-us/library/dwhawy9k.aspx

**Comment by theburningmonk** [comment]
I've published a hotfix version `2.1.1` with this fix

**Comment by zairnamlas** [comment]
Thanks Yan. I'm on holidays and I'll check that next week. Could you please
share the changed loc?

**Comment by theburningmonk** [comment]
Here you go : https://github.com/fsprojects/DynamoDb.SQL/commit/21b5fa49d560b25181ff4f81598defab0bbc3625
